export const mockRow = {
  "id": 2074997,
  "child_trade_set": [
      {
          "id": 2851393,
          "trade_display_volume": "6.00000000",
          "lot_size": "standard",
          "price": "22.50000000",
          "lot_quantity": 6,
          "side": "buy",
          "start_date": "2020-12-01",
          "end_date": "2020-12-31",
          "brokerage_multiplier": 1
      }
  ],
  "lot_unit_name": "bbl",
  "broker_name": "Spectron",
  "trader_name": null,
  "book_name": "Fuel",
  "product_name": "3% GC/3.5% Barges Rot",
  "exchange_name": "ice",
  "source_book_name": null,
  "cancelled": false,
  "matched_trade": null,
  "manual": true,
  "lot_quantity_spread": 0,
  "trade_date": "2019-09-06",
  "exchange_trade_id": null,
  "tas": false,
  "tap": false,
  "rollon_settlement_period": null,
  "screen": false,
  "time_created": "2019-09-06T17:39:16.477417Z",
  "isin": null,
  "trade_type": "block",
  "calendar_period": "monthly",
  "trade_display_volume": "6.00000000",
  "trade_brokerage_multiplier": 1,
  "matched": false,
  "start_date_spread": null,
  "end_date_spread": null,
  "start_date": "2020-12-01",
  "end_date": "2020-12-31",
  "side": "buy",
  "spread": false,
  "trade_price": "22.50000000"
};